version: 2
updates:
- package-ecosystem: pip
  directory: /backend
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    pip-backend-patch-minor:
      patterns:
      - '*'
      update-types:
      - patch
      - minor
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
- package-ecosystem: npm
  directory: /ui
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    npm-ui-patch-minor:
      patterns:
      - '*'
      update-types:
      - patch
      - minor
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    github-actions-root-patch-minor:
      patterns:
      - '*'
      update-types:
      - patch
      - minor
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
